[package]
name = "tp-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.10"
aws-sdk-s3 = "1.64.0"
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
